### ISSUE TITLE
您好，请问evaluation.py中的QApairFile中的文件是什么

### ISSUE THREAD

**Issue by Analongxia** [arthua196/HIT_AnswerSelection_ZWW#1]
您好，我想问一下您的测试集是什么，请问您还有当时的数据集吗？希望您及时回复，谢谢。

**Comment by arthua196** [comment]
你好，这个项目是我的一份作业，测试集在老师那里。因为不清楚版权情况，我刚刚已经删除了训练集和开发集，请不要使用，谢谢！
